name: Test Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action
        id: run_action
        uses: ./
        with:
          spaceId: ${{ vars.SPACE_ID}}
          status: 'current'
          title: "Release: ${{ github.ref_name }}"
          parentId: ${{ vars.PAGE_ID}}
          ConfluenceBaseUrl: 'https://smart-cooking.atlassian.net'
          tag: v1.0.0
          confluence_email: ${{ vars.CONFLUENCE_EMAIL }}
          confluence_api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          appName:   ${{ github.event.repository.name }}
          repoOwner: ${{ github.repository_owner }}
          repoName:  ${{ github.event.repository.name }}

      - name: Clean up
        id: cleanup
        if: success()
        run: |
          # Retrieve the pageId output from the Run action step
          pageId=${{ steps.run_action.outputs.pageId }}
          echo "Page ID: $pageId"
          curl --request DELETE \
          --url 'https://smart-cooking.atlassian.net/wiki/api/v2/pages/$pageId' \
          --user '${{ vars.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_API_TOKEN }}'