name: Test Snyk scan action
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run action
      id: snyk-iac-code-security-checks
      uses: ./ # Uses an action in the root directory
      with:
        SNYK_TOKEN:         ${{ secrets.SNYK_TOKEN }}
        SNYK_ORG_ID:        ${{ secrets.SNYK_ORG_ID }}
        SNYK_PROJECT_NAME:  ${{ secrets.SNYK_PROJECT_NAME }}
        SNYK_PROJECT_ID:    ${{ secrets.SNYK_PROJECT_ID }}
        SEVERITY_THRESHOLD: 'high'
        JSON_FILE_OUTPUT: 'snyk.json'
        FILE: example-*
        update_pr_with_scan_results: true

    - name: Check scan results
      run: |
        # Parse the Snyk scan output
        scan_output=$(cat ${{ steps.snyk-iac-code-security-checks.outputs.JSON_FILE_OUTPUT }})

        # Get the severity level from the previous step
        severity="${{ steps.snyk-iac-code-security-checks.outputs.SEVERITY_THRESHOLD }}"

        # Check the scan output for the specific severity level
        if [[ $scan_output == *"$severity severity"* ]]; then
          echo "Scan results check failed"
          exit 1
        else
          echo "Scan results check passed"
        fi
